require:
  - rubocop-rspec
  - rubocop-rake

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.7
  DisplayCopNames: true
  NewCops: enable
  Exclude:
  - 'geo_combine.gemspec'
  - 'tmp/**/*'

RSpec/DescribeClass:
  Enabled: false

RSpec/BeforeAfterAll:
  Exclude:
    - 'spec/lib/tasks/geo_combine_spec.rb'
