require:
  - rubocop-rspec

plugins:
  - rubocop-rake

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.1
  DisplayCopNames: true
  NewCops: enable
  Exclude:
  - 'geo_combine.gemspec'
  - 'tmp/**/*'
  - 'vendor/bundle/**/*'

RSpec/DescribeClass:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/BeforeAfterAll:
  Exclude:
    - 'spec/lib/tasks/geo_combine_spec.rb'
