name: CI

on: [push]

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Set up Ruby and install dependencies
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3
        bundler-cache: true
    - name: Run linter
      run: bundle exec rubocop

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [3.3, 3.4, 4.0]
    steps:
    - uses: actions/checkout@v6

    - name: Set up Ruby and install dependencies
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: "Run tests for Ruby ${{ matrix.ruby }}"
      run: bundle exec rake spec

    - name: Upload coverage artifacts
      uses: actions/upload-artifact@v6
      with:
        name: "coverage-${{ matrix.ruby }}"
        path: coverage/
